name: Terminator
version: '${project.version}'
main: me.vermeil.terminator.Terminator
api-version: '1.17'
load: STARTUP
authors: [VermeilChan]
description: Terminator is a Spigot plugin inspired by the Terminator from Hypixel Skyblock.
website: https://github.com/VermeilChan/Terminator
commands:
  terminator:
    usage: /terminator getitem
    permission: terminator.give
  giveterminator:
    usage: /giveterminator
    permission: terminator.give
permissions:
  terminator.give:
    default: op
