name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4.6.0
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: 'maven'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: jar-artifact
        path: target/*.jar
